export const TEST_ID = {
  LIST_ITEM: 'list-item',
  LIST_ITEM_TITLE: 'list-item-title',
  LIST_ITEM_SWITCH: 'list-item-switch',
  LIST_ITEM_SWITCH_RESET: 'list-item-switch-reset',
  LIST_ITEM_SWITCH_CHANGE: 'list-item-switch-change',
  LIST_ITEM_SWITCH_ENABLE: 'list-item-switch-enable',
  LIST_ITEM_SWITCH_DISABLE: 'list-item-switch-disable',
  DELETE: 'delete',
  EXPERIMENT_INFO: 'experiment-info',
  OVERRIDE_INPUT: 'override-input',
  SEARCH_INPUT: 'search-input',
  BADGE_ACTIVE: 'badge-active',
  BADGE_ENDED: 'badge-ended',
  BADGE_FUTURE: 'badge-future',
  BADGE_PAUSED: 'badge-paused',
  BADGE_OVERRIDDEN: 'badge-overridden',
  AUTHORS: 'authors',
  FULL_TITLE: 'full-title',
  TAB_SEARCH: 'tab-search',
  SEARCH_RESULT: 'search-result',
  NO_INFO: 'no-info',
}
